### ISSUE TITLE
Windows Build Instructions

### ISSUE THREAD

**Issue by dwalkes** [libyal/libluksde#3] opened 2016-06-21 23:39 UTC
Hi,
Thanks again for sharing this project.
As mentioned in the previous issue post, I was able to build on Mac, install and test.  However, I've so far been unable to build on Windows using the instructions in the Wiki in the [Building](https://github.com/libyal/libluksde/wiki/Building) page.

Since there are no source packages currently on the [downloads](https://github.com/libyal/libluksde/releases) page I've been building from the git source.  I'm wondering if I'm missing a step for Windows builds in this case.

When I checkout and run 

```
./synclibs.sh
```

from MinGW, then try to open Visual Studio, the compile is failing due to "<types.h>".

I noticed a comment in the Visual Studio section which I suspect might be related:

> Note that if you want to build libluksde from source checked out of git with Visual Studio make sure the autotools are able to make a distribution package of libluksde before trying to build it. You can create distribution package by running: "make dist".

However I don't see a "make dist" option in the default makefile.

I thought I'd try running the "Building with MSYS-MinGW" instructions instead.

I wasn't able to run ./autogen.sh using the default MSYS-MinGW, this failed with

> unable to find: pkg-config

I found this mentioned in the MinGW FAQ [here](http://www.mingw.org/wiki/FAQ) and installed [pkg-config-lite](https://sourceforge.net/projects/pkgconfiglite/) to resolve.

However, after installing and running ./autogen.sh I get this error

```
autopoint: *** Missing version: please specify in configure.ac through a line 'AM_GNU_GETTEXT_VERSION(x.yy.zz)' the gettext version the package is using
autopoint: *** Stop.
autoreconf-2.68: autopoint failed with exit status: 1
```

I see this even though configure.ac contains

```
AM_GNU_GETTEXT_VERSION([0.18.1])
```

I've tried removing the brackets as suggested [here](https://answers.launchpad.net/libecbufr/+question/248204) and I've tried changing to x.yy.zz format as well, neither changes the error message.

I'm guessing I might be missing a step related to setting up my environment for the Windows build.

Please let me know if you have any suggestions.

Thanks!

**Comment by joachimmetz** [comment] 2016-06-22 05:04
> Since there are no source packages currently on the downloads page I've been building from the git source. 

Correct, because this project is still very experimental (work in progress)

for Visual Studio you can also use https://github.com/libyal/libluksde/blob/master/autogen.ps1 instead of autogen.sh. 

> However, after installing and running ./autogen.sh I get this error

At first glance this looks like some compatibility issues with gettext/autopoint on MinGW. When I get around to it, I see if I can try to reproduce it.

**Comment by dwalkes** [comment] 2016-06-23 00:21
> for Visual Studio you can also use https://github.com/libyal/libluksde/blob/master/autogen.ps1 instead of autogen.sh.

Thanks, that's what I needed, I didn't notice the powershell scripts before.  The Windows VisualStudio Build works when I use the powershell scripts, with the exception of dokan.  It looks like the dokan links don't work anymore.  I'm assuming I should be using the dokan from https://github.com/dokan-dev/dokany.git?  I'm able to build the latest using instructions at https://github.com/dokan-dev/dokany/wiki/Build (using Visual Studio 2015).  However I keep hitting install issues with https://github.com/dokan-dev/dokany/wiki/Installation#manual-installation.  I haven't been successful with the setup.exe yet either.  I'm trying to use Server 2012 R2 so this might be related, I don't see this specifically listed as supported.  I'll try Windows 8.1 tomorrow.

Let me know if you have any suggestions about a version of dokan to use.  It looks like the version 0.8.0 broke API compatibility so I'm wondering if I need to try a version earlier than that.

**Comment by joachimmetz** [comment] 2016-06-23 05:04
> Thanks, that's what I needed, I didn't notice the powershell scripts before. 

They were created for testing on AppVeyor.

You'll need a patched version of dokan; https://github.com/joachimmetz/dokan. I've not found time to port to dokany yet

**Comment by dwalkes** [comment] 2016-06-25 04:33
> You'll need a patched version of dokan; https://github.com/joachimmetz/dokan. I've not found time to port to dokany yet

Thanks, I was able to build this one and use with libluksde.  I've added changes to the instructions at https://github.com/dwalkes/dokan/commit/deb900b6847f16a452b82144c1ad76bc01f5ac0c and https://github.com/dwalkes/libyal/commit/9f0721662a25101ae2de224368f65d5b5511ff96 let me know if you want a pull request for these.

Now I can run dokan including the mirror example on a Windows 7 32 bit installation.  I'm also able to build luksdemount, libluksde and dokan.dll from the visual studio project.

However I'm still not able to access a luks volume from Windows.
I'm using a disk with encrypted volume starting at sector 0, created with dm-crypt on Linux
I can access this volume on Mac using

```
luksdemount -p test /dev/disk2 /mnt/encrypted_disk
```

However, if I try on Windows

```
luksdemount -p test \\.\PhysicalDrive1 X:
```

I get 

```
Unable to open: \\.\PhysicalDrive1.
libcaes_context_initialize: unable to create AES crypt provider with error: Keys
et does not exist

libluksde_encryption_initialize: unable to initialize decryption context.
libluksde_volume_open_read: unable to create encryption context.
libluksde_volume_open_file_io_handle: unable to read from volume handle.
mount_handle_open_input: unable to open input volume.
```

I noticed the Windows instructions don't include Physical Device access examples, so I copied the encrypted disk image to a file using

```
ddpt if=PD1 of=encrypted.img
```

Then tried

```
luksdemount -p test c:\Users\testlab\encrypted.raw x:
```

However, I see the same error

```
Unable to open: c:\Users\testlab\encrypted.raw.
libcaes_context_initialize: unable to create AES crypt provider with error: Keys
et does not exist

libluksde_encryption_initialize: unable to initialize decryption context.
libluksde_volume_open_read: unable to create encryption context.
libluksde_volume_open_file_io_handle: unable to read from volume handle.
mount_handle_open_input: unable to open input volume.
```

I'll dig into the code to try to understand what's going on and post an update when I figure it out.  Please let me know if you have any suggestions.

**Comment by EricNjue** [comment] 2018-05-14 12:47
@dwalkes were you able to successfully build the library. Am getting an error as attached on the file
[libluksde_error_log.txt](https://github.com/libyal/libluksde/files/2000727/libluksde_error_log.txt)

**Comment by dwalkes** [comment] 2018-05-15 03:24
@EricNjue no I never got past the error above, didn't ever get back to working on this.  It looks like you have gotten further than I have.

**Comment by joachimmetz** [comment] 2018-11-17 10:02
Note that this library is still experimental. See: https://github.com/libyal/libluksde/blob/master/README#L5

I'll have a look when time permits

**Comment by joachimmetz** [comment] 2020-01-01 13:22
> libcaes_context_initialize: unable to create AES crypt provider with error: Keyset does not exist

Duplicate of https://github.com/libyal/libcaes/issues/3

in the mean time:
* Wincrypt support was removed from libcaes https://github.com/libyal/libcaes/issues/10
* DokanY support was added

Closing issue

**Closed as completed by joachimmetz** 2020-01-01 13:22 UTC
Labels: question
